a= input('Digite algo:')
print('tipo primitivo desse valor e:',type(a))
print('tem somente espaco?',a.isspace())
print('e um numero ?',a.isnumeric())
print('e alfabetico?',a.isalpha())
print('e alfanumerico?',a.isalnum())
print('esta em maiusculo ?',a.isupper())
print('esta em minusculo?',a.islower())
print('esta captalizada?',a.istitle())
